version: "3.6"

services:
  simplytranslate:
    build: translate/web/uvicorn/
    image: local/simplytranslate
    container_name: simplytranslate
    # ports:
    #   - "8803:5000"
    volumes:
      - "$PWD/translate/web/config.conf:/etc/simplytranslate/web.conf"
    networks:
      - nginx
    restart: unless-stopped

networks:
  nginx:
    external: true
